#!/bin/sh
# this file is: ~/startAmiberry
#sudo setterm -blank force < /dev/tty1
FOLDER=~/amiberry-rpi4-dmx-32bit
cd $FOLDER
clear
./amiberry --config $FOLDER/conf/a1200-wb31.uae -G
#sudo setterm -blank poke < /dev/tty1
