#!/bin/sh
#sudo setterm -blank force < /dev/tty1
FOLDER=~/amiberry-rpi4-dmx-32bit
cd $FOLDER
clear
sudo nice --19 sudo -u pi ./amiberry --config ~/conf/a1200-wb32.uae -G
#sudo setterm -blank poke < /dev/tty1
